version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: devbook       
      MYSQL_USER: my_user               
      MYSQL_PASSWORD: my_password       
    volumes:
      - mysql-data:/var/lib/mysql 
    restart: unless-stopped   

volumes:
  mysql-data:
